### ISSUE TITLE
User should be able to update their profile

### ISSUE THREAD

**Issue by shahmedme** [raisethevoice/raisethevoice#14]
1. Name
2. Bio
3. Profile picture

**Comment by arafah-dhrubo** [comment]
Work in progress

**Comment by arafah-dhrubo** [comment]
Tested. Everything is working. 
To Update Profile, send PUT request to `/account/profile/:id` this endpoint

**Comment by shahmedme** [comment]
Thanks. Will assign frontend dev to integrate the APIs.

**Comment by srijonashraf** [comment]
Want to work on this issue.

**Comment by robiulhasananim** [comment]
vaiya ami korte cachi ei ta

**Comment by shahmedme** [comment]
Assigned to you @robiulhasananim
