### ISSUE TITLE
Need to add follow suggestion feature

### ISSUE THREAD

**Issue by shahmedme** [raisethevoice/raisethevoice#46]

**Comment by arafah-dhrubo** [comment]
Suppose, you find a issue that is related to your issue. You want to know the updates. As issues are coming randomly. Your following issue may hard to find later.

That's why bookmarking/following issue required in my sense.

**Comment by anikakash** [comment]
yes got it

**Comment by srijonashraf** [comment]
@shahmedme please review the PR of this issue (backend).
